### PR TITLE
fix: fix server side rendering by using type only codemirror import

### PR DESCRIPTION
**Pull request by jgillich**
ref #118

cc @acao this issue was re-introduced in https://github.com/graphql/graphiql/pull/1242

### CODE REVIEW

**Comment by acao** [comment]
thank you! good find

**Comment by jgillich** [comment]
FWIW this fixes it for Next.js dev mode, but I noticed it doesn't actually build, still some `undefined navigator` error from codemirror. I looked into it and I'm I couldn't figure out why this is still happening...

**Comment by acao** [comment]
oops, maybe this is why:

https://github.com/graphql/graphiql/blob/1.0.0/packages/graphiql/src/components/HeaderEditor.tsx#L7

**Comment by jgillich** [comment]
Oof how did realize that. There's one more:

https://github.com/graphql/graphiql/blob/1.0.0/packages/graphiql/src/components/VariableEditor.tsx#L9

but typescript doesn't like it when I remove it:
```
src/components/VariableEditor.tsx:18:14 - error TS2694: Namespace 'CodeMirror' has no exported member 'HintFunction'.

18     hint: CM.HintFunction | CM.AsyncHintFunction;
                ~~~~~~~~~~~~

src/components/VariableEditor.tsx:18:32 - error TS2694: Namespace 'CodeMirror' has no exported member 'AsyncHintFunction'.

18     hint: CM.HintFunction | CM.AsyncHintFunction;
                                  ~~~~~~~~~~~~~~~~~

src/components/VariableEditor.tsx:108:24 - error TS2339: Property 'showHint' does not exist on type 'Editor & { options: any; }'.

108           this.editor!.showHint({
                           ~~~~~~~~

src/components/VariableEditor.tsx:113:24 - error TS2339: Property 'showHint' does not exist on type 'Editor & { options: any; }'.

113           this.editor!.showHint({
                           ~~~~~~~~

src/components/VariableEditor.tsx:118:24 - error TS2339: Property 'showHint' does not exist on type 'Editor & { options: any; }'.

118           this.editor!.showHint({
                           ~~~~~~~~

src/components/VariableEditor.tsx:123:24 - error TS2339: Property 'showHint' does not exist on type 'Editor & { options: any; }'.

123           this.editor!.showHint({
                           ~~~~
```

Any idea what could be done about that? `import type` only works with named imports afaik...

**Comment by jgillich** [comment]
Ok I got it:

```
/// <reference path="../../node_modules/@types/codemirror/addon/hint/show-hint.d.ts" />
```

Not pretty but it works :man_shrugging:
