### ISSUE TITLE
Docs button doesn't work in 0.42 using Firefox

### ISSUE THREAD

**Issue by ndarilek** [graphql/graphiql#65]
I'm attempting to use [this example](https://github.com/jonsharratt/babel-plugin-graphql-js/tree/master/example). Running:

`node index.js`

then hitting http://localhost:3000 in Firefox 42.0 with all addons disabled produces the following unhelpful error when I click Docs:

```

TypeError: e.split is not a function
error source line:
	

...o),t=i+1)}return r}:function(e){return e.split(/\r\n?|\n/)},es=window.getSelecti...

	
graphiql.min.js (line 9, col 824)
```

Seems to work fine in Chrome, but fails in Firefox 42.

Thanks.

**Comment by leebyron** [comment]
Thanks for the report

**Comment by leebyron** [comment]
Hmm, I'm having trouble reproducing this error in FF42. I can open the docs just fine and don't see any error. 

The error is blaming to within CodeMirror itself, that line seems to be https://github.com/codemirror/CodeMirror/blob/1fae53703cf4099d4f4855ef18dd14d60514c82f/lib/codemirror.js#L8531 which isn't used within Docs.

My sense is that touching Docs is triggering a different issue elsewhere, but it's hard for me to investigate without a reproducible case.

@ndarilek is there any way you could host an instances that reliably fails so I can investigate further?

**Comment by ndarilek** [comment]
Huh, so to clarify, you're using the repository/sample I linked to in my 
initial comment?

I ask because according to [this 
issue](https://github.com/jonsharratt/babel-plugin-graphql-js/issues/7), 
@jonsharratt seems to be experiencing the same issue. So if you *are* 
using that example and aren't experiencing it then I'll need to think a 
bit more about what might be causing this.

Thanks.

**Comment by leebyron** [comment]
I was not using that package, I was using the example hosted in this repository.

Let me see if I can get a repro from that package.

**Comment by jonsharratt** [comment]
Hi @leebyron I tried http://graphql-swapi.parseapp.com/ in Firefox and docs did not display.  It takes 3-4 seconds for that error to appear for me.

**Comment by jonsharratt** [comment]
Uploaded a quick video showing what I see in my Firefox on that URL.  If that helps? - Double checked and my version of Firefox is 42.

https://vid.me/N1Dz

**Comment by leebyron** [comment]
Thanks, I've got a repro. This looks like it's newly introduced in FF42 and I think a result of introducing a native version of `fetch`. There is also then not sufficient error handling in GraphiQL to properly display the issue. I'll fix both!
